name: solar system workflow

on: 
  workflow_dispatch: 
  push:
    branches:
      - main
      - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USER }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs: 
    unit-testing:
        name: unit testing
        strategy:
          matrix:
            nodejs_version: [18, 19]
            os: [ubuntu-latest]
            # exclude:
            #   - nodejs_version: 19
            #     os: windows-latest
        runs-on: ${{matrix.os}}


        steps:
        - name: checkout repository
          uses: actions/checkout@v5

        - name: setup nodejs setup
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.nodejs_version}}
        

        - name: cache NPM dependency
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{runner.os}}-node_modules-${{hashFiles('package-lock.json')}}    
       
        - name: install npm dependencies
          run: npm install

        - name: Unit testing
          id: nodejs-unit-testing-step
          run: npm test


        # - name: Archive Test result
        # ## if failureif: failure() && (steps.nodejs-unit-testing-step == 'failure' || steps.nodejs-unit-testing-step == 'success')
        #   if: always()
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: Mocha test resultsss
        #     path: test-resultsa.xml

    code-coverage:
      name: Code coverage
      runs-on: ubuntu-latest
      steps:
        - name: checkout repository
          uses: actions/checkout@v5

        - name: setup nodejs setup
          uses: actions/setup-node@v3
          with:
            node-version: 18
  
        - name: install npm dependencies
          run: npm install

        - name: Check code coverage
          continue-on-error: true
          run: npm run coverage

        # - name: Archive Test result
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: Code Coverage result
        #     path: coverage
        #     retention-days: 5

    docker:
      name: containerization
      needs: [unit-testing,code-coverage]
      runs-on: ubuntu-latest
      steps:
        - name: checkout Repo
          uses: actions/checkout@v5

        - name: Dockerhub login
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Docker build 
          uses: docker/build-push-action@v6
          with:
            context: .
            push: false
            tags: ${{ vars.DOCKERHUB_USERNAME }}/rt8919/solar-system:${{ github.sha }}

        - name: Docker image testing
          run: |
            docker images
            docker run --name solar-system-app -d \
                -p 3000:3000 \
                -e MONGO_URI=$MONGO_URI \
                -e MONGO_USERNAME=$MONGO_USERNAME \
                -e MONGO_PASSWORD=$MONGO_PASSWORD \
                ${{ vars.DOCKERHUB_USERNAME }}//solar-system:${{ github.sha }}

            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
            echo $IP

            echo Testing image URL using wget
            wget -q -O - 127.0.0.1:3000/live | grep live



      



